export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'

export const TEXTS_FETCH_REQUEST = 'TEXTS_FETCH_REQUEST'
export const TEXTS_FETCH_FAILURE = 'TEXTS_FETCH_FAILURE'
export const TEXTS_FETCH_SUCCESS = 'TEXTS_FETCH_SUCCESS'

export const TEXTS_SHOW_REQUEST = 'TEXTS_SHOW_REQUEST'
export const TEXTS_SHOW_FAILURE = 'TEXTS_SHOW_FAILURE'
export const TEXTS_SHOW_SUCCESS = 'TEXTS_SHOW_SUCCESS'

export const TEXTS_CREATE_REQUEST = 'TEXTS_CREATE_REQUEST'
export const TEXTS_CREATE_FAILURE = 'TEXTS_CREATE_FAILURE'
export const TEXTS_CREATE_SUCCESS = 'TEXTS_CREATE_SUCCESS'

export const TEXTS_UPDATE_REQUEST = 'TEXTS_UPDATE_REQUEST'
export const TEXTS_UPDATE_FAILURE = 'TEXTS_UPDATE_FAILURE'
export const TEXTS_UPDATE_SUCCESS = 'TEXTS_UPDATE_SUCCESS'
